#静止spring mvc的自动配置
spring:
  main:
    web-application-type: none

tacocloud:
  email:
    host: imap.qq.com
    mailbox: 425331389@qq.com
    username: 425331389
    password: klxeerictzetbhji
    poll-rate: 10000

  api:
    url: http://localhost:8080/orders/fromEmail